// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAEvSMG32wS2l9gZENqNm9Ig4f1iYiS6Y',
    appId: '1:617279125864:web:5c7a56f47b6e8ed9317edd',
    messagingSenderId: '617279125864',
    projectId: 'e-commerce-application-98afb',
    authDomain: 'e-commerce-application-98afb.firebaseapp.com',
    storageBucket: 'e-commerce-application-98afb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_WXrWu_Bpr625QM7_J8vd17hEyBaJsNI',
    appId: '1:617279125864:android:f23f36219432463e317edd',
    messagingSenderId: '617279125864',
    projectId: 'e-commerce-application-98afb',
    storageBucket: 'e-commerce-application-98afb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh1EllYxiEGBOoDV6KhgxW6q0AdwM_fnY',
    appId: '1:617279125864:ios:5f83284274dd4ec5317edd',
    messagingSenderId: '617279125864',
    projectId: 'e-commerce-application-98afb',
    storageBucket: 'e-commerce-application-98afb.appspot.com',
    androidClientId: '617279125864-421ejmlnpm14ht5utbkr1sgsgnshfct4.apps.googleusercontent.com',
    iosClientId: '617279125864-7rasu3qhe8eoug8m29o2vff3eeii6j0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh1EllYxiEGBOoDV6KhgxW6q0AdwM_fnY',
    appId: '1:617279125864:ios:5f83284274dd4ec5317edd',
    messagingSenderId: '617279125864',
    projectId: 'e-commerce-application-98afb',
    storageBucket: 'e-commerce-application-98afb.appspot.com',
    androidClientId: '617279125864-421ejmlnpm14ht5utbkr1sgsgnshfct4.apps.googleusercontent.com',
    iosClientId: '617279125864-7rasu3qhe8eoug8m29o2vff3eeii6j0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
